# Generated by Django 5.2.6 on 2026-01-30 17:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll_no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('village', models.CharField(default='Karola', max_length=50)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
